export const GET_PHOTO_DATA = "GET_PHOTO_DATA";
export const GET_PHOTO_DATA_SUCCESS = "GET_PHOTO_DATA_SUCCESS";
export const GET_PHOTO_DATA_FAILURE = "GET_PHOTO_DATA_FAILURE";
export const GET_POST_DATA = "GET_POST_DATA";
export const GET_POST_DATA_SUCCESS = "GET_POST_DATA_SUCCESS";
export const GET_POST_DATA_FAILURE = "GET_POST_DATA_FAILURE";
