export const GET_PHOTO_DATA = "GET_PHOTO_DATA";
export const GET_PHOTO_DATA_SUCCESS = "GET_PHOTO_DATA_SUCCESS";
export const GET_PHOTO_DATA_FAILURE = "GET_PHOTO_DATA_FAILURE";
export const GET_POST_DATA = "GET_POST_DATA";
export const GET_POST_DATA_SUCCESS = "GET_POST_DATA_SUCCESS";
export const GET_POST_DATA_FAILURE = "GET_POST_DATA_FAILURE";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_DATA_FAILURE = "GET_USER_DATA_FAILURE";
export const SUBMIT_LOGIN = "SUBMIT_LOGIN";
export const SET_ITEM = "SET_ITEM";
export const RESET_ITEM = "RESET_ITEM";
export const POST_COMMENT = "POST_COMMENT";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";

export const SUBMIT_COMMENT = "SUBMIT_COMMENT";
export const SUBMIT_COMMENT_SUCCESS = "SUBMIT_COMMENT_SUCCESS";
export const SUBMIT_COMMENT_FAILURE = "SUBMIT_COMMENT_FAILURE";

